### ISSUE TITLE
Hashr 2.0 not delegating fetch, keys, etc.

### ISSUE THREAD

**Issue by matthucke** [svenfuchs/hashr#13]
old version:
```
grep hashr Gemfile.lock  # =>    hashr (1.0.0)
foo = Hashr.new
foo.fetch(:other) { "my default" }  # => "my default" 
```

new version:
```
grep hashr Gemfile.lock # => hashr (2.0.0)
foo = Hashr.new
foo.fetch(:other) { "my default" } # => nil
```

Could the hash-like behaviour of "fetch" please be restored?  I also note that other methods on Hash, like keys, size, values, etc., are gone. 

thanks

**Comment by matthucke** [comment]
ping

**Comment by svenfuchs** [comment]
@matthucke that's right, this is on purpose. the previous behaviour has led to a lot of confusion in cases where keys like `merge`, `keys` etc were defined vs users were trying to use the respective Hash methods.

I'd suggest converting the Hashr instance to a Hash in places where you need these methods (e.g. `foo.to_h.fetch(:other)`), or having  a look at https://github.com/svenfuchs/hashr/tree/master/lib/hashr/delegate for restoring them.
