### ISSUE TITLE
add to_hashr method to ruby hash class for convinience.

### ISSUE THREAD

**Issue by zw963** [svenfuchs/hashr#20]
```rb
class Hash
  def to_hashr
    Hashr.new(self)
  end
end
```

Thanks

**Comment by svenfuchs** [comment]
@zw963 Thanks a lot for the suggestion! 

I'd much rather not modify Ruby core classes though. Please add such convenience code on your side.

**Comment by zw963** [comment]
@svenfuchs , i don't understand what you means, anywhy, this gem was extend core hash class with `deep_symbolize_keys` and `deep_merge`, and add a new `to_hashr`, i don't think have any issue.

Thanks
